name: Tests

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16.10.0
      env:
        DOCKER: true

    steps:
      - uses: actions/checkout@v2

      - name: Own all files
        run: USER=$(/usr/bin/id -run) && chown -R $USER ./

      - name: Install dependencies
        run: npm ci

      - name: Check that build succeeds
        run: npm run build

      - name: Run unit tests
        run: npm test
        env:
          CI: true
          NODE_ENV: 'test'

      - name: Report test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.1.1
        with:
          skip-step: all # we already ran the tests, no need to run again
