name: Validate

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: node:18.17.0
      env:
        DOCKER: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Own all files
        run: USER=$(/usr/bin/id -run) && chown -R $USER ./

      - name: Install dependencies
        run: npm ci

      - name: Generate version
        run: npm run export-version

      - name: Check that linting succeeds
        run: npm run lint

      - name: Check that build succeeds
        run: npm run build

      - name: Run unit tests
        run: npm test

      # - name: Report test coverage
      #   uses: ArtiomTr/jest-coverage-report-action@v2.2.2
